### ISSUE TITLE
request: download attribute

### ISSUE THREAD

**Issue by Spacewalker2** [fronbasal/serve#1]
Hello,

it would be cool if links open direct as a download dialog. This is possible by using the download attribute (https://stackoverflow.com/a/16316830). Maybe this can be switched on and off by using a cli parameter.

Thanks.

**Comment by fronbasal** [comment]
Very interesting idea. I will look into that.

**Comment by fronbasal** [comment]
Sadly this idea was abandoned by the Golang maintainers: https://go-review.googlesource.com/c/go/+/151981

I will attempt to write a custom handler.
